name: tsne
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip

  # Base conda deps
  - setuptools
  - setuptools_scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel
  - pytest
  - pytest-cov

  # This project conda deps
  - cython
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - notebook
  - jupyterlab

  - pip:
    # This project pip deps
